name: Docker Image Build Workflow
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        tag:
          - jsk_enshu
          - ros_melodic_cuda9.2
          - ros_melodic_cuda10.2
          - ros_noetic_cuda11.3.1_torch1.10
    name: build_${{ matrix.tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.tag }}
          push: false
          tags: tkmtnt7000/ubuntu-ros:${{ matrix.tag }}